targets:
  $default:
    builders:
      slang_build_runner:
        options:
          namespaces: false
          input_directory: lib/core/i18n
          input_file_pattern: .yaml
          output_directory: lib/zgen/i18n
      source_gen|combining_builder:
        # Оптимизация скорости генерации
        generate_for:
          include:
            - lib/**.cg.dart
        # Изменение пути вывода
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/zgen/{{}}.g.dart"
      # theme_tailor:
      #   generate_for:
      #     include:
      #       - lib/theme/app_theme.cg.dart
      #   options:
      #     themes: [light]
      #     build_extensions:
      #       "^lib/{{}}.dart": "lib/zgen/{{}}.tailor.dart"
