name: ya_mafia
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^13.2.1
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  slang_build_runner: ^3.30.0
  icons_launcher: ^2.1.7
  freezed: ^2.4.7

flutter:
  uses-material-design: true

analyzer:
  errors:
    invalid_annotation_target: ignore
