name: ya_mafia
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  dio: ^5.4.1
  flip_board: ^1.0.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_tts: 3.8.5
  freezed_annotation: ^2.4.1
  go_router: ^13.2.1
  pretty_dio_logger: ^1.3.1
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  slang_build_runner: ^3.30.0
  theme_tailor: ^3.0.1
  icons_launcher: ^2.1.7
  freezed: ^2.4.7
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/mafia_icons/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700

analyzer:
  errors:
    invalid_annotation_target: ignore
