// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBusm_GZNgSFS3hM0q5MCdV_UJb0oaB4ng',
    appId: '1:774931490115:web:b31b3662573501bb75fbf6',
    messagingSenderId: '774931490115',
    projectId: 'ya-mafia',
    authDomain: 'ya-mafia.firebaseapp.com',
    storageBucket: 'ya-mafia.appspot.com',
    measurementId: 'G-H7LBE2KJFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJ8kwWxcjwGY1gRdLUeIied0dphQw_BQ',
    appId: '1:774931490115:android:c53a87fd19facfbd75fbf6',
    messagingSenderId: '774931490115',
    projectId: 'ya-mafia',
    storageBucket: 'ya-mafia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAohwkCVQT8sq03jyEtTGmhr2Iqi1J7_vM',
    appId: '1:774931490115:ios:546220ec8fa1a89e75fbf6',
    messagingSenderId: '774931490115',
    projectId: 'ya-mafia',
    storageBucket: 'ya-mafia.appspot.com',
    iosBundleId: 'com.example.yaMafia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAohwkCVQT8sq03jyEtTGmhr2Iqi1J7_vM',
    appId: '1:774931490115:ios:f5b214f37e5c4b6c75fbf6',
    messagingSenderId: '774931490115',
    projectId: 'ya-mafia',
    storageBucket: 'ya-mafia.appspot.com',
    iosBundleId: 'com.example.yaMafia.RunnerTests',
  );
}
